#!/usr/bin/env bash

# Usage: $0 <source/nixos/> [dry-run]
# Takes targeted nix tree and syncs it to your /etc/nixos/
# ensures owner and permissions are correct

set -euo pipefail  # Exit on errors, undefined vars, pipe failures


# Default paths
NIXPKGS="/nix/var/nix/profiles/per-user/root/channels/nixos"
NIXOS_DIR="/etc/nixos"

SOURCE="${1:-}"
DRY_RUN="${2:-false}"

# Validate arguments
if [ -z "$SOURCE" ]; then
    echo "Usage: $0 <source_directory> [dry-run]"
    echo "  source_directory: Path to your targeted nix tree"
    echo "  dry-run: 'true' to preview changes without applying them"
    exit 1
fi

if [ ! -d "$SOURCE" ]; then
    echo "Error: Source directory does not exist: $SOURCE"
    exit 1
fi

if [ ! -d "$NIXOS_DIR" ]; then
    echo "Error: NIXOS_DIR does not exist: $NIXOS_DIR"
    exit 1
fi

# Ensure trailing slash on SOURCE
case "$SOURCE" in
    */) ;;
    *) SOURCE="${SOURCE}/" ;;
esac

# Create backup BEFORE syncing
BACKUP_DIR="$NIXOS_DIR/backup"
mkdir -p "$BACKUP_DIR"

if [ ! -f "$NIXOS_DIR/configuration.nix" ]; then
    echo "Error: $NIXOS_DIR/configuration.nix not found"
    exit 1
fi

BACKUP_FILE="$BACKUP_DIR/configuration.nix.$(date +%Y%m%d%H%M%S)"
echo "Creating backup of configuration.nix..."
sudo cp "$NIXOS_DIR/configuration.nix" "$BACKUP_FILE"

if [ ! -f "$NIXOS_DIR/hardware-configuration.nix" ]; then
    echo "Warning: hardware-configuration.nix not found, skipping"
else
    BACKUP_HARDWARE="$BACKUP_DIR/hardware-configuration.nix.$(date +%Y%m%d%H%M%S)"
    echo "Creating backup of hardware-configuration.nix..."
    sudo cp "$NIXOS_DIR/hardware-configuration.nix" "$BACKUP_HARDWARE"
fi

# Dry-run mode
if [ "$DRY_RUN" = "true" ]; then
    echo "Dry-run mode enabled - no changes will be made"
    echo "Would copy: $SOURCE -> $NIXOS_DIR"
    echo "Would preserve permissions from original files"
    echo "Would exclude: hardware-configuration, configuration.nix.save*"
    exit 0
fi

# Copy hardware-configuration.nix first (it's generated by nixos-hardware)
sudo cp /etc/nixos/hardware-configuration.nix "$SOURCE"

# Copy configuration.nix.save if it exists, otherwise create backup
if [ -f /etc/nixos/configuration.nix.save ]; then
    sudo cp /etc/nixos/configuration.nix.save "$SOURCE"
else
    echo "Warning: /etc/nixos/configuration.nix.save not found, creating backup."
    sudo cp /etc/nixos/configuration.nix "$BACKUP_DIR/configuration.nix.backup"
fi

# Sync files with rsync
# --exclude: Skip hardware-configuration and .save files
# --no-owner --no-group: Preserve original permissions from source
# --delete: Remove files in destination that don't exist in source
sudo rsync -a --delete --no-owner --no-group \
    --exclude 'hardware-configuration' \
    --exclude 'configuration.nix.save*' \
    "$SOURCE" "$NIXOS_DIR"/

# Set ownership on synced files
sudo chown root:root -R "$NIXOS_DIR"

echo "Sync complete!"
echo "Backup saved to: $BACKUP_DIR"
