# ~/.config/hypr/partials/monitors.conf
# hyprctl monitors

# Laptop
monitor=eDP-1, 1920x1080, 0x0, 1

# Work
monitor = DVI-I-1, 1920x1080@60, 3840x0, 1
monitor = DVI-I-2, 1920x1080@60, 1920x0, 1

# Home Desk (New)
# Acer Technologies KG271U N3 3539279673W01
monitor=HDMI-A-1, 2560x1440@144.00Hz, 0x0, 1
# Acer Technologies KA272U TJJAA0013E00
monitor=HDMI-A-2, 2560x1440@74.60Hz, 2560x0, 1, transform, 3

# For the future
#monitorv2 {
  #output = DP-1
  #mode = 1920x1080@144
  #position = 0x0
  #scale = 1
  #transform = 2
#}
