# ~/.config/hypr/partials/workspaces.conf

# Give yourself aliases for the monitor descriptions:
$KG271U = desc:Acer Technologies KG271U N3 3539279673W01
$KA272U = desc:Acer Technologies KA272U TJJAA0013E00
$CB242Y = desc:Acer Technologies CB242Y TH7AA0012451

# Workspace-to-monitor mapping (New Desktop)
workspace = 1, $KG271U
workspace = 2, $KG271U
workspace = 3, $KG271U
workspace = 4, $KG271U
workspace = 5, $KG271U
# --------------------
workspace = 6, $KA272U
workspace = 7, $KA272U
workspace = 8, $KA272U
workspace = 9, $KA272U

# Workspaces
exec-once = [workspace 1] thunderbird
exec-once = [workspace 2] kitty --name=fastfetch -e bash -c "tmux new-session 'fastfetch; curl --connect-timeout 3 --max-time 3 wttr.in/New-York?M; exec bash'"
exec-once = [workspace 3] firefox

